<?php
/**
 * @file
 * tieto_new_concept_page.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function tieto_new_concept_page_default_fe_block_settings() {
  $export = array();

  $export['version'] = '2.0';

  $export['views-230b594481d6ee8fad0731a51afaf5cc'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => '230b594481d6ee8fad0731a51afaf5cc',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'tietocom' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tietocom',
        'weight' => -24,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-b3b8101dcff870d9b59e936365a95cff'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'b3b8101dcff870d9b59e936365a95cff',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'tietocom' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tietocom',
        'weight' => -20,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-be1a0779c1c32795777037ac476cd0e4'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'be1a0779c1c32795777037ac476cd0e4',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'tietocom' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tietocom',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-career_cases-block_1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'career_cases-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'tietocom' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tietocom',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-career_follow_us-block_1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'career_follow_us-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'tietocom' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tietocom',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-career_highlight-block_1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'career_highlight-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'tietocom' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tietocom',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-careers_team-block_1'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'careers_team-block_1',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'tietocom' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tietocom',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  $export['views-concept_page_menu-block'] = array(
    'cache' => -1,
    'custom' => 0,
    'delta' => 'concept_page_menu-block',
    'i18n_block_language' => array(),
    'i18n_mode' => 0,
    'module' => 'views',
    'node_types' => array(
      0 => 'concept_page',
    ),
    'pages' => '',
    'roles' => array(),
    'themes' => array(
      'bartik' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'bartik',
        'weight' => 0,
      ),
      'tietocom' => array(
        'region' => '',
        'status' => 0,
        'theme' => 'tietocom',
        'weight' => 0,
      ),
    ),
    'title' => '',
    'visibility' => 0,
  );

  return $export;
}
