<?php
/**
 * @file
 * tieto_new_concept_page.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
function tieto_new_concept_page_user_default_permissions() {
  $permissions = array();

  // Exported permission: 'create career_cases content'.
  $permissions['create career_cases content'] = array(
    'name' => 'create career_cases content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'create careers_highlight content'.
  $permissions['create careers_highlight content'] = array(
    'name' => 'create careers_highlight content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'create careers_team content'.
  $permissions['create careers_team content'] = array(
    'name' => 'create careers_team content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'create concept_page content'.
  $permissions['create concept_page content'] = array(
    'name' => 'create concept_page content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'delete any career_cases content'.
  $permissions['delete any career_cases content'] = array(
    'name' => 'delete any career_cases content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'delete any careers_highlight content'.
  $permissions['delete any careers_highlight content'] = array(
    'name' => 'delete any careers_highlight content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'delete any careers_team content'.
  $permissions['delete any careers_team content'] = array(
    'name' => 'delete any careers_team content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'delete any concept_page content'.
  $permissions['delete any concept_page content'] = array(
    'name' => 'delete any concept_page content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'delete own career_cases content'.
  $permissions['delete own career_cases content'] = array(
    'name' => 'delete own career_cases content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'delete own careers_highlight content'.
  $permissions['delete own careers_highlight content'] = array(
    'name' => 'delete own careers_highlight content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'delete own careers_team content'.
  $permissions['delete own careers_team content'] = array(
    'name' => 'delete own careers_team content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'delete own concept_page content'.
  $permissions['delete own concept_page content'] = array(
    'name' => 'delete own concept_page content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'edit any career_cases content'.
  $permissions['edit any career_cases content'] = array(
    'name' => 'edit any career_cases content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'edit any careers_highlight content'.
  $permissions['edit any careers_highlight content'] = array(
    'name' => 'edit any careers_highlight content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'edit any careers_team content'.
  $permissions['edit any careers_team content'] = array(
    'name' => 'edit any careers_team content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'edit any concept_page content'.
  $permissions['edit any concept_page content'] = array(
    'name' => 'edit any concept_page content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'edit own career_cases content'.
  $permissions['edit own career_cases content'] = array(
    'name' => 'edit own career_cases content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'edit own careers_highlight content'.
  $permissions['edit own careers_highlight content'] = array(
    'name' => 'edit own careers_highlight content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'edit own careers_team content'.
  $permissions['edit own careers_team content'] = array(
    'name' => 'edit own careers_team content',
    'roles' => array(),
    'module' => 'node',
  );

  // Exported permission: 'edit own concept_page content'.
  $permissions['edit own concept_page content'] = array(
    'name' => 'edit own concept_page content',
    'roles' => array(),
    'module' => 'node',
  );

  return $permissions;
}
