<?php
/**
 * @file
 * Code for the Tieto Top Story feature.
 */

include_once 'tieto_top_story.features.inc';

/**
 * Implements hook_menu_breadcrumb_alter().
 */
function tieto_top_story_menu_breadcrumb_alter(&$active_trail, $item) {
  if (($node = menu_get_object()) && in_array($node->type, array('tieto_top_story', 'tieto_customer_reference_case'))) {
    $active_trail[1] = array(
      'title' => t('Customer cases'),
      'href' => dirname(url('node/'. $node->nid)),
      'localized_options' => array(),
    );
  }
}

/**
 * Implements hook_preprocess_views_view_rss().
 */
function tieto_top_story_preprocess_views_view_rss(&$vars) {
  if ($vars['view']->name == 'top_stories' && $vars['view']->current_display == 'top_stories_feed') {
    // Set top stories feed's link point to main top stories page.
    $vars['link'] = url('top-stories', array('absolute' => TRUE));
  }
}
