<?php
/**
 * @file
 * tieto_materialbank.file_type.inc
 */

/**
 * Implements hook_file_default_types().
 */
/*
function tieto_materialbank_file_default_types() {
  $export = array();

  $file_type = new stdClass();
  $file_type->disabled = FALSE;
  $file_type->api_version = 1;
  $file_type->type = 'webpage';
  $file_type->label = 'Webpage';
  $file_type->mimetypes = array('text/html');
  $file_type->description = 'A Webpage is a remote entity.';
  $export['webpage'] = $file_type;

  return $export;
}
*/