<?php
/**
 * @file
 * tieto_landing_page.features.user_permission.inc
 */

/**
 * Implements hook_user_default_permissions().
 */
/*
function tieto_landing_page_user_default_permissions() {
  $permissions = array();

  // Exported permission: administer search api exclude.
  $permissions['administer search api exclude'] = array(
    'name' => 'administer search api exclude',
    'roles' => array(
      'Administrator' => 'Administrator',
      'Sysop' => 'Sysop',
    ),
    'module' => 'search_api_exclude',
  );

  return $permissions;
}*/
