<?php

/**
 * Implements hook_ctools_plugin_api().
 */
function feeds_hugin_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_hugin_feeds_plugins() {
  return array(
    'FeedsHuginParser' => array(
      'name' => t('Hugin hexML parser'),
      'description' => t('Parse Hugin hexML.'),
      'handler' => array(
        'parent' => 'FeedsParser',
        'class' => 'FeedsHuginParser',
        'file' => 'FeedsHuginParser.inc',
        'path' => drupal_get_path('module', 'feeds_hugin'),
      ),
    ),
  );
}

/**
 * Implements hook_hook_info().
 */
function feeds_hugin_hook_info() {
  $hooks = array(
    'feeds_hugin_sources_alter',
    'feeds_hugin_press_releases_alter',
  );

  return array_fill_keys($hooks, array('group' => 'feeds_hugin'));
}

