<?php
/**
 * @file
 * tieto_worldwide.variable.inc
 */

/**
 * Implements hook_variable_realm_default_variables().
 */
function tieto_worldwide_variable_realm_default_variables() {
$realm_variables = array();
  $realm_variables['language']['cs'] = array(
  'googleanalytics_account' => 'UA-7407225-4',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/83631',
  'site_frontpage' => 'node/3457',
  'site_name' => 'tieto.cz',
  'site_slogan' => '',
);
  $realm_variables['language']['da'] = array(
  'googleanalytics_account' => 'UA-7407225-3',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/20886',
  'site_name' => 'Tieto.dk',
  'site_slogan' => '',
);
  $realm_variables['language']['de'] = array(
  'googleanalytics_account' => 'UA-7407225-5',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/83636',
  'site_frontpage' => 'node/3577',
  'site_name' => 'tieto.de',
  'site_slogan' => '',
);
  $realm_variables['language']['de-at'] = array(
  'googleanalytics_account' => 'UA-7407225-19',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/3495',
  'site_name' => 'tieto.at',
  'site_slogan' => '',
);
  $realm_variables['language']['en'] = array(
  'googleanalytics_account' => 'UA-46059866-1',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');
ga(\'create\', \'UA-7407225-3\', \'auto\', {\'name\': \'t3\'});
ga(\'t3.send\', \'pageview\');',
  'maintenance_mode_message' => 'Tieto\'s external web is currently under maintenance. We should be back shortly. Thank you for your patience.',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/3480',
  'site_name' => 'tieto.com',
  'site_slogan' => '',
);
  $realm_variables['language']['en-in'] = array(
  'googleanalytics_account' => 'UA-7407225-9',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/251',
  'site_name' => 'tieto.in',
  'site_slogan' => '',
);
  $realm_variables['language']['et'] = array(
  'googleanalytics_account' => 'UA-7407225-7',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/239',
  'site_name' => 'tieto.ee',
  'site_slogan' => '',
);
  $realm_variables['language']['fi'] = array(
  'googleanalytics_account' => 'UA-46058589-1',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');
ga(\'create\', \'UA-7407225-8\', \'auto\', {\'name\': \'t3\'});
ga(\'t3.send\', \'pageview\');',
  'maintenance_mode_message' => 'Tieto\'s external web is currently under maintenance. We should be back shortly. Thank you for your patience.',
  'site_403' => '',
  'site_404' => 'node/83626',
  'site_frontpage' => 'node/3478',
  'site_name' => 'tieto.fi',
  'site_slogan' => '',
);
  $realm_variables['language']['fil'] = array(
  'googleanalytics_account' => 'UA-7407225-3',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/51661',
  'site_name' => 'Tieto.ph',
  'site_slogan' => '',
);
  $realm_variables['language']['lt'] = array(
  'googleanalytics_account' => 'UA-7407225-11',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/3462',
  'site_name' => 'tieto.lt',
  'site_slogan' => '',
);
  $realm_variables['language']['lv'] = array(
  'googleanalytics_account' => 'UA-7407225-12',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/3461',
  'site_name' => 'tieto.lv',
  'site_slogan' => '',
);
  $realm_variables['language']['nl'] = array(
  'googleanalytics_account' => 'UA-7407225-13',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/3481',
  'site_name' => 'tieto.nl',
  'site_slogan' => '',
);
  $realm_variables['language']['nn'] = array(
  'googleanalytics_account' => 'UA-46058592-1',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');
ga(\'create\', \'UA-7407225-14\', \'auto\', {\'name\': \'t3\'});
ga(\'t3.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/83611',
  'site_frontpage' => 'node/3484',
  'site_name' => 'tieto.no',
  'site_slogan' => '',
);
  $realm_variables['language']['pl'] = array(
  'googleanalytics_account' => 'UA-7407225-15',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/3486',
  'site_name' => 'tieto.pl',
  'site_slogan' => '',
);
  $realm_variables['language']['ru'] = array(
  'googleanalytics_account' => 'UA-7407225-16',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/3266',
  'site_name' => 'tieto.ru',
  'site_slogan' => '',
);
  $realm_variables['language']['sv'] = array(
  'googleanalytics_account' => 'UA-45708653-1',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');
ga(\'create\', \'UA-7407225-17\', \'auto\', {\'name\': \'t3\'});
ga(\'t3.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/83641',
  'site_frontpage' => 'node/448',
  'site_name' => 'tieto.se',
  'site_slogan' => '',
);
  $realm_variables['language']['zh-hans'] = array(
  'googleanalytics_account' => 'UA-7407225-20',
  'googleanalytics_codesnippet_after' => 'ga(\'create\', \'UA-7407225-28\', \'auto\', {\'name\': \'t2\'});
ga(\'t2.send\', \'pageview\');',
  'site_403' => '',
  'site_404' => 'node/80171',
  'site_frontpage' => 'node/3453',
  'site_name' => 'tieto.cn',
  'site_slogan' => '',
);

return $realm_variables;
}
