<?php 
/**
 * @file
 * Adds a Slideshare feed processor to the Feeds module.
 */

/**
 * Implements ctools_plugin_api().
 */

function feeds_sldieshare_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implements hook_feeds_plugins().
 */
function feeds_slideshare_feeds_plugins() {
  $info = array();
  $info['FeedsSlideshareParser'] = array(
    'name' => 'Slideshare parser',
    'description' => 'Parse Slideshare feeds.',
    'help' => 'Use PHP SimpleXML parser to parse Slideshare feeds.',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FeedsSlideshareParser',
      'file' => 'FeedsSlideshareParser.inc',
      'path' => drupal_get_path('module', 'feeds_slideshare'),
    ),
  );
  return $info;
}
